#166840963 setup redux
andela/ah-nyati-frontend pull request #4
Opened 2019-07-31 17:25 UTC by chokonaira

#### What does this PR do?

- Setup Redux

#### Description of Task to be completed?

- Integrated Redux to Authors Haven
- Created the appropriate folder/file structure for React/Redux workflow

#### How should this be manually tested?

- Install redux-developer-tools extension chrome
- npm run build
- npm start
- open chrome dev-tools to view connection on the redux terminal

#### Any background context you want to provide?

- redux-developer-tools extension

#### What are the relevant pivotal tracker stories?

-[#166840963](https://www.pivotaltracker.com/story/show/166840963) 

#### Screenshots (if appropriate)

<img width="1279" alt="Screenshot 2019-07-31 at 6 13 36 PM" src="https://user-images.githubusercontent.com/38280567/62233408-6fa9c300-b3c0-11e9-8480-a6f9f1993569.png">

#### Questions:

-N/A

2019-07-31 17:29 UTC, Cavdy requested changes
You have commented out code... Please delete it

2019-07-31 19:02 UTC, Alpha1202 approved these changes
Great Job @chokonaira

2019-07-31 22:52 UTC, Cavdy approved these changes

2019-08-01 15:31 UTC, phembarl approved these changes

2019-08-02 14:39 UTC, merged